# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: 'gd'
  filter_sets:
    miniature:
      quality: 75
      filters:
        thumbnail:
          size: [600, 600]
    pictureFilter:
      quality: 75
      filters:
        scale:
          dim: [600, 600]
    pictureFull:
      quality: 85
      filters:
        scale:
          dim: [1200, 1200]
    watermark_filter:
      filters:
        # use and setup the "watermark_image" filter
        watermark_image:
          # path to the watermark file (prepended with "%kernel.project_dir%")
          image: public/img/watermark.png
          # size of the water mark relative to the input image
          size: 0.3
          # set the position of the watermark
          position: multiple
    interlace_filter:
      filters:
        # use and setup the "interlace" filter
        interlace:
          # set the interlace mode to line
          mode: partition
