# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: 'gd'
  filter_sets:
    miniature:
      quality: 75
      filters:
        thumbnail:
          size: [600, 600]
    pictureFilter:
      quality: 75
      filters:
        scale:
          dim: [600, 600]
    pictureFull:
      quality: 85
      filters:
        scale:
          dim: [1200, 1200]
