vich_uploader:
  db_driver: orm

  mappings:
    picture_images:
      uri_prefix: '%picture_images%'
      upload_destination: '%kernel.project_dir%/public%picture_images%'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_update: false
      delete_on_remove: false
